ARG PYTHON_VERSION=3.11
FROM python:${PYTHON_VERSION}-bullseye

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    postgresql-client \
    netcat-openbsd \
    openssl \
 && rm -rf /var/lib/apt/lists/*

ENV PIP_CACHE_DIR=/root/.cache/pip
ENV PIP_PROGRESS_BAR=off

# ---- сначала продовые зависимости (кэшируются) ----
COPY requirements.auth.txt .
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install --no-cache-dir -r requirements.auth.txt

# ---- потом тестовые (очень быстрые) ----
COPY tests/requirements.test.auth.txt tests/requirements.test.auth.txt
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install --no-cache-dir -r tests/requirements.test.auth.txt

# ---- копируем весь код ----
COPY . .

WORKDIR /app
ENTRYPOINT ["/app/tests/entrypoint.test.auth.sh"]
